### ISSUE TITLE
Improve warning message when api server cannot be reached

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-command-line-services#181]
When configuring CLI, you need to define the following information for authentication. But if you provide incorrect **apiURL**, there is no clear message for this configuration in CLI pod as well as for CLI command:

**CLI Pod Error:**
`[err] An error occurred. An error occurred during authentication for user [mtamboli]. Unexpected char 60 at (line no=1, column no=1, offset=0)`

**Error on the `kabanero login` command:**
`An internal error occurred`

**Misconfigured apiURL:**
```
  github:
    apiUrl: https://github.com
    organization: myorg
    teams:
    - my team

```
